"""Shared types and the wire contract.

Internal records are stdlib dataclasses. Everything that crosses the socket is
built by a ``*_wire`` helper and checked by :func:`validate_event` against
``WIRE_SCHEMA`` — a mirror of the frontend's ``src/types/events.ts``. An event
missing a key, or carrying an unknown type, fails loudly in the engine rather
than silently dropping a trace in the UI.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# --------------------------------------------------------------------------
# Corpus
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Document:
    doc_id: str  # sha256(bytes)[:16] — content addressed
    label: str  # short display label used in citations, e.g. Doc_3
    title: str
    source: str  # path relative to the corpus root
    kind: str  # document | transcript | pdf
    text: str
    #: Transcripts only: [(speaker, start_s, end_s, text)]
    turns: tuple[tuple[str, float, float, str], ...] = ()


@dataclass(frozen=True)
class Chunk:
    chunk_id: str
    doc_id: str
    doc_label: str
    section: str  # the citation section marker, <=24 chars, no ']'
    heading: str  # human heading trail, or speaker + time range
    text: str
    ordinal: int
    kind: str = "document"

    @property
    def citation(self) -> str:
        return f"[{self.doc_label} §{self.section}]"

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "doc_id": self.doc_id,
            "doc_label": self.doc_label,
            "section": self.section,
            "heading": self.heading,
            "text": self.text,
            "ordinal": self.ordinal,
            "kind": self.kind,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Chunk":
        return cls(**data)


# --------------------------------------------------------------------------
# Streaming + retrieval
# --------------------------------------------------------------------------


class Decision(str, Enum):
    WAIT = "wait"
    RETRIEVE = "retrieve"
    SUPPRESS = "suppress"
    REFINE = "refine"


@dataclass(frozen=True)
class TranscriptChunk:
    text: str
    at_ms: int


@dataclass
class SubQuery:
    id: str
    text: str
    source: str = "decomposed"  # provisional | decomposed | refine
    span: str = ""
    confidence: float = 1.0
    #: When set, results were reused from this provisional sub-query.
    reused_from: str | None = None


@dataclass
class Hit:
    chunk: Chunk
    score: float
    branches: list[str]
    sub_query_ids: list[str]
    rrf: float = 0.0

    def to_wire(self) -> dict[str, Any]:
        return {
            "chunkId": self.chunk.chunk_id,
            "docId": self.chunk.doc_label,
            "section": self.chunk.section,
            "text": self.chunk.text,
            "score": round(float(self.score), 4),
            "branches": list(self.branches),
            "subQueryIds": list(self.sub_query_ids),
            "citation": self.chunk.citation,
            # Extra, ignored by the TS contract but useful to a reader.
            "heading": self.chunk.heading,
        }


@dataclass
class SubQueryResult:
    sub_query: SubQuery
    candidates: int
    kept: list[Hit]
    branch_counts: dict[str, int] = field(default_factory=dict)
    reranked: bool = False
    elapsed_ms: float = 0.0


@dataclass(frozen=True)
class Claim:
    id: str
    text: str  # sentence as shipped, citation markers included
    chunk_ids: tuple[str, ...]
    sub_query_id: str
    support: float

    def to_wire(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "text": self.text,
            "chunkIds": list(self.chunk_ids),
            "subQueryId": self.sub_query_id,
            "support": round(float(self.support), 3),
        }


@dataclass(frozen=True)
class AnswerVersion:
    version: int
    parent: int | None
    claims: tuple[Claim, ...]
    preserved: tuple[str, ...]
    mutated: tuple[str, ...]
    uncertainty: tuple[str, ...]
    full_corpus_search: bool
    body: str = ""
    citation_support_rate: float = 1.0
    fabricated_citations: int = 0  # shipped — 0 by construction
    fabricated_blocked: int = 0  # generated by the model, stripped before shipping


# --------------------------------------------------------------------------
# Wire contract — mirror of Samsung-fd/src/types/events.ts
# --------------------------------------------------------------------------

#: required keys per server event type (optional keys listed separately)
WIRE_SCHEMA: dict[str, tuple[set[str], set[str]]] = {
    "session.ready": ({"sessionId", "corpus"}, set()),
    "turn.start": ({"turnId"}, set()),
    "transcript.chunk": ({"turnId", "text", "atMs"}, set()),
    "controller.decision": ({"turnId", "decision", "reason", "atMs"}, {"confidence"}),
    "retrieval.started": ({"turnId", "subQueryId", "trigger", "atMs"}, {"query"}),
    "retrieval.cancelled": ({"turnId", "subQueryId", "reason"}, set()),
    "utterance.end": ({"turnId", "atMs"}, set()),
    "subqueries": ({"turnId", "items"}, set()),
    "retrieval.result": ({"turnId", "subQueryId", "candidates", "kept"}, {"reused"}),
    "fusion.final": ({"turnId", "hits", "quotaApplied", "fullCorpusSearch"}, set()),
    "answer.token": ({"turnId", "version", "text"}, set()),
    "answer.version": (
        {
            "turnId",
            "version",
            "parent",
            "claims",
            "preserved",
            "mutated",
            "uncertainty",
            "citationSupportRate",
            "fabricatedCitations",
        },
        set(),
    ),
    "turn.complete": ({"turnId", "latencyMs", "cost"}, set()),
    "error": ({"code", "message"}, {"turnId"}),
}

CLIENT_EVENTS = {"utterance.start", "utterance.chunk", "utterance.end", "replay", "session.new"}
DECISIONS = {d.value for d in Decision}
TRIGGERS = {"provisional", "multi_intent", "refine"}
SUBQUERY_SOURCES = {"provisional", "decomposed"}


class WireError(ValueError):
    pass


def validate_event(event: dict[str, Any]) -> dict[str, Any]:
    kind = event.get("type")
    if kind not in WIRE_SCHEMA:
        raise WireError(f"unknown server event type {kind!r}")
    required, optional = WIRE_SCHEMA[kind]
    keys = set(event) - {"type"}
    missing = required - keys
    extra = keys - required - optional
    if missing or extra:
        raise WireError(f"{kind}: missing={sorted(missing)} extra={sorted(extra)}")
    if kind == "controller.decision" and event["decision"] not in DECISIONS:
        raise WireError(f"bad decision {event['decision']!r}")
    if kind == "retrieval.started" and event["trigger"] not in TRIGGERS:
        raise WireError(f"bad trigger {event['trigger']!r}")
    if kind == "subqueries":
        for item in event["items"]:
            if set(item) != {"id", "text", "source"} or item["source"] not in SUBQUERY_SOURCES:
                raise WireError(f"bad sub-query item {item!r}")
    return event
